media:
  input: media
  output: /media
  categories: [image]

content:
  - name: products
    label: Products
    type: collection
    path: content/products
    format: json
    fields:
      - name: name
        label: Product Name
        type: string
      - name: price
        label: Price
        type: number
      - name: image
        label: Product Image
        type: image
      - name: description
        label: Description
        type: string
      - name: details
        label: More Details
        type: text
      - name: available
        label: Available
        type: boolean

  - name: stories
    label: Stories
    type: collection
    path: content/stories
    format: json
    fields:
      - name: title
        label: Story Title
        type: string
      - name: date
        label: Date
        type: date
      - name: image
        label: Story Image
        type: image
      - name: content
        label: Story
        type: text
      - name: published
        label: Published
        type: boolean
  - name: yuyuhoon
    label: Yuyuhoon
    type: file
    path: content/yuyuhoon.json
    format: json
    fields:
      - name: subtitle
        label: Subtitle
        type: string
      - name: introduction
        label: Introduction
        type: text
      - name: facts
        label: Facts
        type: list
        field:
          type: string
