content:
  - name: products
    label: Products
    type: collection
    path: content/products
    format: json
    fields:
      - name: name
        label: Product Name
        type: string
        required: true

      - name: price
        label: Price
        type: number
        required: true

            - name: image
        label: Product Image
        type: image
        options:
          path: assets/products
        required: true

      - name: description
        label: Description
        type: text

      - name: available
        label: Available
        type: boolean
